channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy
  - xarray
  - netcdf4
  - intake
  - intake-xarray
  - pyviz::bokeh  
  - pyviz::datashader
  - pyviz::holoviews  
  - pyviz::geoviews
  - pyviz::hvplot  
  - pyviz::panel
